#!/bin/bash

###############################################################
# ks-tools - Initialize the ks-tools ZUI (using xterm)        #
# Date: 02-01-2022                                            #
# Author: q3aql                                               #
# Contact: q3aql@duck.com                                     #
###############################################################
VERSION="8.0 (BETA)"
M_DATE="020122"

# Variables
name_terminal="ks-tools v${VERSION} (${M_DATE})"
term="xterm"
font="Monospace"
size_font="11"
color_b="black"
color_f="white"
rcfile="/usr/share/ks-tools/ks-tools-rc"
command="ks-zui"

# Command to run
${term} -T "${name_terminal}" -fa ${font} -fs ${size_font} -bg ${color_b} \
-fg ${color_f} -e ${command}
