#!/bin/bash

###############################################################
# ks-tools - Initialize the ks-tools terminal (using xterm)   #
# Date: 03-05-2021                                            #
# Author: q3aql                                               #
# Contact: q3aql@protonmail.ch                                #
###############################################################
VERSION="7.3"
M_DATE="030521"

# Variables
name_terminal="ks-tools v${VERSION} (${M_DATE})"
term="xterm"
font="Monospace"
size_font="11"
color_b="black"
color_f="white"
rcfile="/usr/share/ks-tools/ks-tools-rc"
command="bash --rcfile ${rcfile}"

# Command to run with xterm (Disabled)
#${term} -T "${name_terminal}" -fa ${font} -fs ${size_font} -bg ${color_b} \
#-fg ${color_f} -e ${command}

# Command to run with native terminal
${command}
